### ISSUE TITLE
64-bit compatibility 

### ISSUE THREAD

**Issue by mdyszynski** [q-depot/ciXtract#1]
Hi,

Im working on a cinder application which I'm building in 64-bit (X86_64) architecture. ciXtract throws a bunch of errors if built in anything other than i386. Is there a version of ciXtract compatible with 64-bit cinder applications?

Hope you can help!

**Comment by q-depot** [comment]
Hi, try to pull the master branch, I've compiled the osx libraries for x86_64 and i386, that should fix it.

**Comment by mdyszynski** [comment]
Fantastic. Thanks a lot!
