### ISSUE TITLE
Offline feature extraction

### ISSUE THREAD

**Issue by mdyszynski** [q-depot/ciXtract#2]
Hi,

How would I go about extracting features from a whole track at once rather than what's in the current buffer? Hope you can help.

**Comment by q-depot** [comment]
Hi,

for offline analysis I'd recommend to switch to SonicVisualiser, it's a good tool and it let you export the data to XML.

http://www.sonicvisualiser.org/

SonicVisualiser supports plugins, check out the LibXtract and the Queen Mary plugin set here:
http://www.vamp-plugins.org/download.html

**Comment by mdyszynski** [comment]
Thanks for the fast response!

SonicVisualiser is a standalone application which is not what Im looking for. I need to extract features from a list of tracks within the (cinder) application I'm working on. ciXtract does this well in real-time (as the track is playing) but I really want to get ciXtract to extract features from all these tracks offline (analyse each song and then store and use this data). Is there a way to achieve this?

**Comment by q-depot** [comment]
I suggest you to ask on the Cinder forum, this question is more related to the Cinder audio api. 
As long as you can pass the correct PCM buffer to ciXtract, whether you do it in real-time or offline, it shouldn't make any difference.
